version: '1'
services:
  db:
    image: postgres:latest
    container_name: 62teknologi-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

  be:
    build:
      context: .
    container_name: 62teknologi-be
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
